### ISSUE TITLE
File install libelf

### ISSUE THREAD

**Issue by ghost** [jedavies-dev/kiss-armv7#1]
Build Failed "in expansion of macro ELFTC_ARCH"

**Comment by jedavies-dev** [comment]
@ricardoG08: added override for libelf, please test.

**Comment by ghost** [comment]
ok i will ignore libelf, what bootloader do you recommend installing?

**Comment by jedavies-dev** [comment]
Can you build libelf OK now?  Please close the issue if so.

Regarding the bootloader, I use uboot on the Pinebook Pro. What you should use depends on what device you have.

However note that uboot is not available for KISS armv7 yet. I'm using a uboot image I built from my aarch64 repo:  https://github.com/jedavies-dev/kiss-aarch64

I'm working on adding uboot and ARM firmware for armv7, will add to this repo when it's done.

If you are using a Pinebook Pro, you can use the uboot binaries that comes with the stock Manjaro by following the "U-Boot" section of this tutorial where dd is used to write to the boot device: https://stikonas.eu/wordpress/2019/09/15/blobless-boot-with-rockpro64/

**Comment by ghost** [comment]
I don't know how to add "override", sorry but I don't know how to speak English, but I try.

**Comment by jedavies-dev** [comment]
No problem :)
The override is just the libelf package in this repo and should be detected automatically if this repo comes before the standard KISS repo in your KISS_PATH environment variable, like:

KISS_PATH=/var/db/kiss/kiss-armv7/repo:/var/db/kiss/repo/core:/var/db/kiss/repo/extra:/var/db/kiss/repo/xorg:/var/db/kiss/repo/testing

It means that when you do "kiss b libelf" it will build the version from the armv7 repo, which I have now patched to work on armv7.  The armv7 version will "override" the normal x86_64 version.

So you should now be able to build libelf on armv7.

**Comment by jedavies-dev** [comment]
Basically if you do:
`kiss u`

then:
`kiss b libelf`

...it should work OK now.
